version: "3.9"

name: case5-link-shortener

services:
  database:
    build: ./database
    container_name: case5-db
    environment:
      MYSQL_ROOT_PASSWORD: "case5rootpass"
      MYSQL_DATABASE: "shorten_link"
      MYSQL_USER: "case5user"
      MYSQL_PASSWORD: "case5pass"
    volumes:
      - ./database/dbdata:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: case5-backend
    environment:
      DB_HOST: database
      DB_PORT: "3306"
      DB_USER: case5user
      DB_PASS: case5pass
      DB_NAME: shorten_link
      DB_MAX_RETRIES: "60"
      DB_RETRY_DELAY: "2s"
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: case5-frontend
    restart: unless-stopped

  gateway:
    build: ./gateaway
    container_name: case5-gateway
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
